# example stages
# see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml
stages:
  download:
    cmd: bash stages/1_download.sh 
    deps:
      - stages/1_download.sh
    outs:
      - download
  
  brick:
    cmd: bash stages/2_build.sh
    deps:
      - download
      - stages/2_build.sh
      - stages/zinc2parquet.py
    outs:
      - brick/zinc.parquet